### ISSUE TITLE
API tracer

### ISSUE THREAD

**Issue by SpeaklessAmanda** [decaf-project/DECAF#74]
It seems that only the Windows API function can be hooked. I am trying to hook  the underlying c language implementation of PHP, I just cannot get any reult. Does decaf only hook Windows API?

**Comment by hengyin** [comment]
For Windows VMI, there is a list of modules for symbol extraction. The
function you hook must be an export function for that module, and that
module must appear in this list. If not, you can add your module in this
list, so the offsets of export functions in that module can be resolved.

https://github.com/decaf-project/DECAF/blob/master/decaf/shared/windows_vmi.cpp#L92


Thanks,
Heng
