### ISSUE TITLE
build fails

### ISSUE THREAD

**Issue by expnkx** [decaf-project/DECAF#77]
CC    i386-softmmu/smbios.o
  CC    i386-softmmu/wdt_ib700.o
  CC    i386-softmmu/debugcon.o
  CC    i386-softmmu/multiboot.o
  CC    i386-softmmu/pc_piix.o
  CC    i386-softmmu/monitor.o
  LINK  i386-softmmu/qemu-system-i386
/usr/bin/ld: ../libhw64/9pfs/virtio-9p.o: in function `stat_to_v9stat':
/home/cqwrteur/www/DECAF/decaf/hw/9pfs/virtio-9p.c:1037: undefined reference to `minor'
/usr/bin/ld: /home/cqwrteur/www/DECAF/decaf/hw/9pfs/virtio-9p.c:1037: undefined reference to `major'
/usr/bin/ld: ../libhw64/9pfs/virtio-9p.o: in function `v9fs_create':
/home/cqwrteur/www/DECAF/decaf/hw/9pfs/virtio-9p.c:2221: undefined reference to `makedev'
/usr/bin/ld: ../libhw64/9pfs/virtio-9p.o: in function `v9fs_mknod':
/home/cqwrteur/www/DECAF/decaf/hw/9pfs/virtio-9p.c:2852: undefined reference to `makedev'
collect2: error: ld returned 1 exit status
make[1]: *** [Makefile:436: qemu-system-i386] Error 1
make: *** [Makefile:100: subdir-i386-softmmu] Error 2

**Comment by expnkx** [comment]
Compiler version

cqwrteur@cqwrteur-Precision-Tower-5810:~/www/decaf_release/DECAF-1.91/decaf$ g++ -v
Using built-in specs.
COLLECT_GCC=g++
COLLECT_LTO_WRAPPER=/usr/local/libexec/gcc/x86_64-pc-linux-gnu/10.0.1/lto-wrapper
Target: x86_64-pc-linux-gnu
Configured with: ../gcc/configure --enable-languages=c,c++,lto --disable-bootstrap --with-pkgversion=cqwrteur : (reconfigured) ../gcc/configure --disable-bootstrap --with-pkgversion=cqwrteur --enable-languages=c,c++,lto --no-create --no-recursion
Thread model: posix
Supported LTO compression algorithms: zlib
gcc version 10.0.1 20200206 (experimental) (cqwrteur)

**Comment by enlighten5** [comment]
Hi,
This seems to be a glibc incompatible issue. Glibc removes sys/sysmacros.h which defines `makedev` and `minor`from sys/types.h since v2.28.
Can you check your glibc version by `ldd --version`. Mine is glibc 2.23 and it works fine. 
This patch may be helpful if your glibc version is higher: https://github.com/chaos/diod/issues/44

**Comment by expnkx** [comment]
> Hi,
> This seems to be a glibc incompatible issue. Glibc removes sys/sysmacros.h which defines `makedev` and `minor`from sys/types.h since v2.28.
> Can you check your glibc version by `ldd --version`. Mine is glibc 2.23 and it works fine.
> This patch may be helpful if your glibc version is higher: [chaos/diod#44](https://github.com/chaos/diod/issues/44)

Is that possible to fix it in decaf project directly? Is it an upstream bug?

My GCC is latest 10.0.1 since I need C++20 supports

**Comment by enlighten5** [comment]
Yes, you do not need to downgrade your glibc or GCC. I think this can be easily solved by adding `#include <sys/sysmacros.h>`  in `hw/9pfs/virtio-9p.c`. Can you try that to see if it works?

**Comment by expnkx** [comment]
Fixed
